# Exercise 6

(14 points)

Write a function that, given an invertible matrix $A$, returns a list of elementary matrices whose product is $A$.

Hint: Think of how we produced the inverse of a matrix as a product of elementary matrices by doing row operations, that transformed the matrix into the unit matrix. From the list of these row operations we can easily produce the required list of elementary matrices.
    
    
    

As a warmup, given a matrix $A$, you can produce a list consisting of elementary matrices and a single matrix in row echelon form, such that the product of the matrices in this list gives back A. For this you can freely modify the code below. If you get this far you get 7 points.

In [21]:
# you can, but you don't need to use (parts of) this code
#    - feel free to write your solution from scratch, if you prefer that!
def row_echelon(given_matrix):
    """
    Returns a matrix in row echelon form obtained from the given_matrix.
    """
    elementary_mat = []
    # make a copy so that we don't change the original matrix
    mat = given_matrix.copy()
    nr_rows,nr_columns=mat.shape
    # The algorithm runs through all the columns
    start_row = 0
    for current_column in range(nr_columns):
        # every iteration ignores one more column, if we found a zero column, 
        # or one more row and column otherwise
        # in each iteration go down the current leftmost column:
        for r in range(start_row, nr_rows):
            # find the first row with a nonzero entry in first column
            if r!=nr_rows-1: continue
            if mat[r][current_column] == 0:
                # case 1: we have a zero entry, but are not yet at the bottom row. 
                # Go to the next iteration of the inner for loop
                # and consider the next entry in this column.
                if r!=nr_rows-1:
                    continue
                # case 2: we arrived at the last row so we have a zero column. 
                # Go back to the outer for loop and consider the next column    
                else:
                    break
            # if we arrived here we have found a non-zero entry in row r.
            # Then swap our starting row with the first row
            """The .copy() was missing here before, causing the attempted row switching to overwrite a row"""
            mat[start_row], mat[r] = mat[r].copy(), mat[start_row].copy()
            # now add multiples of the new first row to lower rows
            # such that lower entries of the current column become zero
            upper_left_entry = mat[start_row][current_column]
            for rr in range(start_row+1, nr_rows):
                entry_that_should_become_zero = mat[rr][current_column]
                scalar_multiple = -1 * entry_that_should_become_zero / upper_left_entry
                mat[rr] += mat[start_row] * scalar_multiple
                # This for loop will increase the process time significantly
                # for cc in range(current_column, nr_columns):
                    # mat[rr][cc] += mat[start_row][cc] * scalar_multiple
            # The current start row will not be changed anymore
            start_row += 1
    return mat


In [164]:
import numpy as np
def elementary_matrices(given_matrix):
# you can, but you don't need to use (parts of) this code
#    - feel free to write your solution from scratch, if you prefer that!
    """
    Returns a matrix in row echelon form obtained from the given_matrix.
    """
    elementary_mat = []
    # make a copy so that we don't change the original matrix
    mat = given_matrix.copy()
    nr_rows,nr_columns=mat.shape
    # The algorithm runs through all the columns
    start_row = 0
    for current_column in range(nr_columns):
        # every iteration ignores one more column, if we found a zero column, 
        # or one more row and column otherwise
        # in each iteration go down the current leftmost column:
        for r in range(start_row, nr_rows):
            # find the first row with a nonzero entry in first column
            if r!=nr_rows-1: continue
            if mat[r][current_column] == 0:
                # case 1: we have a zero entry, but are not yet at the bottom row. 
                # Go to the next iteration of the inner for loop
                # and consider the next entry in this column.
                if r!=nr_rows-1:
                    continue
                # case 2: we arrived at the last row so we have a zero column. 
                # Go back to the outer for loop and consider the next column    
                else:
                    break
            # if we arrived here we have found a non-zero entry in row r.
            # Then swap our starting row with the first row
            """The .copy() was missing here before, causing the attempted row switching to overwrite a row"""
            eye_mat = np.eye(given_matrix.shape[0])
            eye_mat[start_row], eye_mat[r] = eye_mat[r].copy(), eye_mat[start_row].copy()
            mat = eye_mat@mat
            elementary_mat.append(np.linalg.inv(eye_mat))
            # now add multiples of the new first row to lower rows
            # such that lower entries of the current column become zero
            upper_left_entry = mat[start_row][current_column]
            for rr in range(start_row+1, nr_rows):
                entry_that_should_become_zero = mat[rr][current_column]
                scalar_multiple = -1 * entry_that_should_become_zero / upper_left_entry
                eye_mat = np.eye(given_matrix.shape[0])
                eye_mat[rr] += eye_mat[start_row] * scalar_multiple
                mat = eye_mat@mat
                elementary_mat.append(np.linalg.inv(eye_mat))
                # This for-loop will increase the process time significantly
                # for cc in range(current_column, nr_columns):
                    # mat[rr][cc] += mat[start_row][cc] * scalar_multiple
            # The current start row will not be changed anymore
            start_row += 1
    '''
    Thanks a lot for the help in trianglize the matrix.

    What we'll do next is a column-by-column operation. First, we
    normalize the diagonal entry of a column (by scalar mul to 1).
    Then we use the entry to "punch" some holes out of the rest row entires above.
    '''
    for current_column in range(nr_columns-1, -1, -1):
        # Contrary to the previous step, this loop begins from the bottom right corner
        start_row -= 1
        # Normalize the bottom entry of the column
        bottom_right_entry = mat[start_row][current_column]
        eye_mat = np.eye(given_matrix.shape[0])
        eye_mat[start_row] = eye_mat[start_row]/bottom_right_entry
        mat = eye_mat@mat
        elementary_mat.append(np.linalg.inv(eye_mat))            
        for rr in range(start_row-1, -1, -1):
            # No let's dig some holes happlily with 1
            entry_that_should_become_zero = mat[rr][current_column]
            scalar_multiple = -1 * entry_that_should_become_zero
            eye_mat = np.eye(given_matrix.shape[0])
            eye_mat[rr] += eye_mat[start_row] * scalar_multiple
            mat = eye_mat@mat
            elementary_mat.append(np.linalg.inv(eye_mat))            
    return elementary_mat

# Note: the code is still quite dirty since there are lots of repititions which may be designed into a proper function.

In [165]:
A = np.random.random([500,500])
B = np.eye(5)
for C in elementary_matrices(A):
    B = B@C
print(B)


[[0.17146994 0.40580726 0.91089326 0.97102122 0.7201784 ]
 [0.83074188 0.20311005 0.89197834 0.08723748 0.73238416]
 [0.5032368  0.93236474 0.53722972 0.69401395 0.46615619]
 [0.62203011 0.36383473 0.57299155 0.52438375 0.61447901]
 [0.05027931 0.69642257 0.44804713 0.61610559 0.71615777]]


Your function should be such that the following code returns $\texttt{True}$ (also for other matrices than the concrete $A$ below, of course). Testing $\texttt{A==B}$ might not exactly return $\texttt{True}$ because of rounding errors or data type issues. So here is a test looking at whether the two matrices are close to each other.

(the test looks for the matrix distance in the $\ell_1$-norm on the vector space of matrices, in the terminology of the lecture. In practice the threshold can be taken to be much closer to zero than 0.01)

In [166]:
import numpy as np
A=np.array([[1.,2.,3.],[1.,1.,1.],[5.,2.,1.]])
B=np.eye(3)
for C in elementary_matrices(A):
    B=B@C

def matrix_distance(A,B):
    sum_of_differences = 0
    for i in range(len(B)):
        for j in range(len(B[i])):
            sum_of_differences += abs(A[i,j]-B[i,j]) 
    return sum_of_differences

matrix_distance(A,B)<0.01


True