In [138]:
from collections import Counter
import string
import re
import itertools
import numpy as np

Task1

In [8]:
file = open('C:\\Users\\shouc\\Desktop\\学习_进行中\\HHU\\course\\ML\\exercise\\exercise1\\hhu_wikipedia.txt',encoding='UTF-8', errors='ignore')
page = file.read()
print(page)

Heinrich Heine University Düsseldorf (abbr. HHU; German: Heinrich-Heine-Universität Düsseldorf) is a public university in North Rhine-Westphalia, Germany, which was founded in 1965 as the successor organisation to Düsseldorf's Medical Academy of 1907 and was named after German poet Heinrich Heine.

Following several expansions throughout the decades, the university has comprised five faculties since 1993. Currently, more than 36,000 full-time students are studying at HHU. There is a total staff of approximately 3,600 persons at HHU (academic and non-academic).

History

Facilities of the Faculty of Arts and Humanities. The background to the right shows construction works of the Faculty of Mathematics and Natural Sciences (around 1973).
Düsseldorf University began with the Düsseldorf Academy for Practical Medicine in 1907. The city's first real university, however, was only founded in 1965 by adding a combined Faculty of Natural Sciences–Arts and Humanities to the existing medical one. 

In [9]:
file.close()

In [13]:
frequency = page.count('Mathematics')

In [48]:
word_c = re.sub(r'[^\w\s]', '', page).lower().split(" ")
word_freq = Counter(word_c)
top_ten = word_freq.most_common(10)
print(top_ten)

[('the', 146), ('and', 116), ('of', 78), ('in', 67), ('for', 34), ('research', 34), ('a', 31), ('to', 27), ('faculty', 24), ('as', 23)]


Task2

In [136]:
def m_transpose(m, n):
    i0 = i1 = [i for i in range(n)]
    i_m = list(itertools.product(i0,i1))
    m1 = [m[i[1]][i[0]] for i in i_m]
    m11 = [[]]*n
    for j in range(n):
        m11[j].append(m1[j*n:(j+1)*n])        
    return m1

In [137]:
print(m_transpose([[1,2,3],[4,5,6],[7,8,9]], 3))

[1, 4, 7, 2, 5, 8, 3, 6, 9]


In [139]:
def det_cal(m):
    m0 = np.array(m)
    det = np.linalg.det(m0)
    return det

In [141]:
print(det_cal([[1,2,3],[4,5,6],[7,8,9]]))

-9.51619735392994e-16


In [162]:
def m_mult(m,n):
    m1 = np.zeros((3,3))
    m=np.array(m)
    n=np.array(n)
    for i in range(3):
        for j in range(3):
            m1[i][j] = np.sum(np.dot(m[i,:],n[:,j]))
    return m1

In [163]:
print(m_mult([[1,1,1],[2,2,2],[3,3,3]],[[1,3,2],[5,2,2],[4,6,9]]))

[[10. 11. 13.]
 [20. 22. 26.]
 [30. 33. 39.]]
