In [10]:
import numpy as np

A = np.random.randint(0, 100, (5, 5))
B = np.random.randint(0, 100, (5, 1))
print(A); print(B)


[[22 32 87 31 20]
 [57 39  5 52 89]
 [92 81 27 28 82]
 [91 52 22 79  3]
 [19 10 14 51 92]]
[[35]
 [77]
 [ 9]
 [12]
 [ 8]]


In [11]:
A@B


array([[ 4549],
       [ 6379],
       [10692],
       [ 8359],
       [ 2909]])

In [12]:
A.dot(B)


array([[ 4549],
       [ 6379],
       [10692],
       [ 8359],
       [ 2909]])

In [14]:
np.multiply(A,B)


array([[ 770, 1120, 3045, 1085,  700],
       [4389, 3003,  385, 4004, 6853],
       [ 828,  729,  243,  252,  738],
       [1092,  624,  264,  948,   36],
       [ 152,   80,  112,  408,  736]])