In [1]:
# Open and read the content of the text
# The content will remain after closing the file
path = "data/hhu_wikipedia.txt"
file = open(path)
content = file.read()
file.close()

In [2]:
content

'Heinrich Heine University Düsseldorf (abbr. HHU; German: Heinrich-Heine-Universität Düsseldorf) is a public university in North Rhine-Westphalia, Germany, which was founded in 1965 as the successor organisation to Düsseldorf\'s Medical Academy of 1907 and was named after German poet Heinrich Heine.\n\nFollowing several expansions throughout the decades, the university has comprised five faculties since 1993. Currently, more than 36,000 full-time students are studying at HHU. There is a total staff of approximately 3,600 persons at HHU (academic and non-academic).\n\nHistory\n\nFacilities of the Faculty of Arts and Humanities. The background to the right shows construction works of the Faculty of Mathematics and Natural Sciences (around 1973).\nDüsseldorf University began with the Düsseldorf Academy for Practical Medicine in 1907. The city\'s first real university, however, was only founded in 1965 by adding a combined Faculty of Natural Sciences–Arts and Humanities to the existing med

In [3]:
# There are lots of unwanted characters to be cleaned.
# The capitalized letters can also be lowered.
import re

cleaned_content = re.sub(r"\'s", " ", content) # HHU's/Düsseldorf's
cleaned_content = re.sub(r"[^a-zA-ZäöüÄÖÜ\s]", " ", content)

# cleaned_content = cleaned_content.lower()

# Split the cleaned data to a list of words
cleaned_content = cleaned_content.split()
cleaned_content

['Heinrich',
 'Heine',
 'University',
 'Düsseldorf',
 'abbr',
 'HHU',
 'German',
 'Heinrich',
 'Heine',
 'Universität',
 'Düsseldorf',
 'is',
 'a',
 'public',
 'university',
 'in',
 'North',
 'Rhine',
 'Westphalia',
 'Germany',
 'which',
 'was',
 'founded',
 'in',
 'as',
 'the',
 'successor',
 'organisation',
 'to',
 'Düsseldorf',
 's',
 'Medical',
 'Academy',
 'of',
 'and',
 'was',
 'named',
 'after',
 'German',
 'poet',
 'Heinrich',
 'Heine',
 'Following',
 'several',
 'expansions',
 'throughout',
 'the',
 'decades',
 'the',
 'university',
 'has',
 'comprised',
 'five',
 'faculties',
 'since',
 'Currently',
 'more',
 'than',
 'full',
 'time',
 'students',
 'are',
 'studying',
 'at',
 'HHU',
 'There',
 'is',
 'a',
 'total',
 'staff',
 'of',
 'approximately',
 'persons',
 'at',
 'HHU',
 'academic',
 'and',
 'non',
 'academic',
 'History',
 'Facilities',
 'of',
 'the',
 'Faculty',
 'of',
 'Arts',
 'and',
 'Humanities',
 'The',
 'background',
 'to',
 'the',
 'right',
 'shows',
 'construc

In [4]:
cleaned_content.count("Mathematics")

5

In [5]:
# Extract the unique words as keys for the "count" method
keys = list(set(cleaned_content))
frequencies = [cleaned_content.count(key) for key in keys]

for x in range(10):
    # Find the index of the word with highest frequency
    index = frequencies.index(max(frequencies))
    # Output the exact word through the index
    print("No. {} Word: \"{}\" Frequency: {}".format(x+1, keys[index], frequencies[index]))
    # Remove/Pop the word out of the list
    frequencies.pop(index)
    keys.pop(index)

No. 1 Word: "the" Frequency: 135
No. 2 Word: "and" Frequency: 116
No. 3 Word: "of" Frequency: 78
No. 4 Word: "in" Frequency: 65
No. 5 Word: "for" Frequency: 34
No. 6 Word: "a" Frequency: 30
No. 7 Word: "to" Frequency: 27
No. 8 Word: "HHU" Frequency: 25
No. 9 Word: "Düsseldorf" Frequency: 23
No. 10 Word: "as" Frequency: 22


In [2]:
# try to construct function by oneself and compare with numpy built-in functions
# 3x3 only
import numpy as np

A = np.random.random((3,3))

def transpose(A):
    B = A.copy()
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            A[i,j] = B[j, i]
    return B

print(transpose(A))
print(A.T)

[[0.1260084  0.26644761 0.2157037 ]
 [0.93952935 0.60325221 0.28975549]
 [0.59896688 0.14173158 0.24435719]]
[[0.1260084  0.26644761 0.2157037 ]
 [0.93952935 0.60325221 0.28975549]
 [0.59896688 0.14173158 0.24435719]]


In [3]:
def determinant_3(A):
    det = 0
    for i in range(3):
        det += A[0,i%3]*A[1,(i+1)%3]*A[2,(i+2)%3]
        det -= A[0,i%3]*A[1,(i-1)%3]*A[2,(i-2)%3]
    return det

print(determinant_3(A))
print(np.linalg.det(A))

-0.0507447754820314
-0.050744775482031386


In [10]:
B = np.random.random((3,4))

In [20]:
def matmul(A, B):
    assert A.shape[1] == B.shape[0]
    C = np.empty((A.shape[0],B.shape[1]))
    for i in range(C.shape[0]):
        for j in range(C.shape[1]):
            C[i, j] = sum(A[i,:]*B[:, j])
    return C


print(matmul(A, B))
print(A@B)

[[0.95315666 0.76211931 0.70825422 0.16290373]
 [0.62368115 0.29661322 0.40844492 0.10353013]
 [0.31711683 0.32418477 0.41814388 0.06385889]]
[[0.95315666 0.76211931 0.70825422 0.16290373]
 [0.62368115 0.29661322 0.40844492 0.10353013]
 [0.31711683 0.32418477 0.41814388 0.06385889]]
